name: Build derivative logos

on:
  push:
    branches: ["logos"]
  pull_request:
    branches: ["logos"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo dnf install -y imagemagick just
      - name: Build derivative logos
        run: just build
      - uses: actions/upload-artifact@v3
        name: Upload built logos
        with:
          name: logos
          path: out/
